SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-d7s6qqt7vvec73eejjmg-a:5432/casemanagement
SPRING_DATASOURCE_USERNAME=casemanagement_user
SPRING_DATASOURCE_PASSWORD=R4D1CbbZ2RaWtghDZOrv5R5NXz6CxQKX
JWT_SECRET=super-secret-key-12345678901234567890